### ISSUE TITLE
Lambda broken

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#92]
```
{
    "errorMessage": "Could not locate Gemfile or .bundle/ directory",
    "errorType": "Init<Bundler::GemfileNotFound>",
    "stackTrace": [
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:288:in `rescue in root'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:284:in `root'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:95:in `bundle_path'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:684:in `configure_gem_home'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:665:in `configure_gem_home_and_path'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:81:in `configure'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:194:in `definition'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:143:in `setup'",
        "/var/runtime/gems/bundler-2.2.23/lib/bundler.rb:174:in `require'",
        "/var/task/lib/rdf2marc.rb:4:in `<top (required)>'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/task/lambda_function.rb:4:in `<top (required)>'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
    ]
}
```

Presumably caused by https://github.com/LD4P/rdf2marc/pull/90

**Comment by jcoyne** [comment]
This might just be that we need to set BUNDLE_GEMFILE=/var/task/Gemfile

Possibly can do this with `ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)`
