### ISSUE TITLE
rdf2marc failing with failure to load

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#95]
In development, requesting MARC conversion of https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4

![image](https://user-images.githubusercontent.com/588335/133147233-76ab7d94-0e60-4af8-b162-3066cdf7a314.png)

Best guess is this is related to recent caching changes. Note that calls to Sinopia API should not be cached.

**Comment by jcoyne** [comment]
@justinlittman there is a small problem in the code, but the bigger problem is that the specified record doesn't exist:
```
$ curl -i https://api.stage.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4
HTTP/2 404
date: Mon, 13 Sep 2021 21:23:41 GMT
content-type: text/plain; charset=utf-8
content-length: 9
access-control-allow-origin: *
access-control-expose-headers: Location,Content-Location
content-security-policy: default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
x-dns-prefetch-control: off
expect-ct: max-age=0
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=15552000; includeSubDomains
x-download-options: noopen
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
x-xss-protection: 0
etag: W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"

Not Found
```

**Comment by justinlittman** [comment]
` https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4` not ` https://api.stage.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4`

**Comment by justinlittman** [comment]
```
{
    "errorMessage": "Unable to load https://api.development.sinopia.io/resource/4bf07817-38a4-41d5-8498-8a9a36b88ec4",
    "errorType": "Function<Rdf2marc::BadRequestError>",
    "stackTrace": [
        "/var/task/lib/rdf2marc/graphs_loader.rb:45:in `rescue in from_uri'",
        "/var/task/lib/rdf2marc/graphs_loader.rb:42:in `from_uri'",
        "/var/task/lib/rdf2marc/graphs_loader.rb:7:in `from_instance_uri'",
        "/var/task/lambda_function.rb:18:in `lambda_handler'"
    ]
}
```

**Comment by justinlittman** [comment]
```
{
    "errorMessage": "Read-only file system @ dir_s_mkdir - cache",
    "errorType": "Function<Errno::EROFS>",
    "stackTrace": [
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:211:in `each'",
        "/var/lang/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache/file_store.rb:164:in `ensure_cache_path'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache/file_store.rb:87:in `write_entry'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache/strategy/local_cache.rb:165:in `write_entry'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache.rb:476:in `block in write'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache.rb:726:in `block in instrument'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications.rb:205:in `instrument'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache.rb:726:in `instrument'",
        "/opt/ruby/gems/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/cache.rb:474:in `write'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache/storage.rb:58:in `write'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:259:in `store'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:285:in `block in fetch'",
        "/opt/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:283:in `fetch'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:187:in `process'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:135:in `call!'",
        "/opt/ruby/gems/2.7.0/gems/faraday-http-cache-2.2.0/lib/faraday/http_cache.rb:115:in `call'",
        "/opt/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'",
        "/opt/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'",
        "/opt/ruby/gems/2.7.0/gems/faraday-1.7.1/lib/faraday/connection.rb:200:in `get'",
        "/var/task/lib/rdf2marc.rb:40:in `open_url'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/util/file.rb:307:in `open_file'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/reader.rb:221:in `open'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/mixin/mutable.rb:44:in `load'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:124:in `block (2 levels) in load'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:123:in `each'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:123:in `block in load'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:163:in `initialize'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:122:in `new'",
        "/opt/ruby/gems/2.7.0/gems/rdf-3.1.15/lib/rdf/repository.rb:122:in `load'",
        "/var/task/lib/rdf2marc/graphs_loader.rb:43:in `from_uri'",
        "/var/task/lib/rdf2marc/graphs_loader.rb:7:in `from_instance_uri'",
        "/var/task/lambda_function.rb:18:in `lambda_handler'"
    ]
}
```

**Comment by jcoyne** [comment]
It looks like we might have misconfigured the cache to use the filestore rather than s3.

**Comment by justinlittman** [comment]
Fixed
